### ISSUE TITLE
stack implementation

### ISSUE THREAD

**Issue by longxueyuu** [skx/go.vm#12]
I'm just curious, that is,
why is the **stack** implemented as fisrt-in-first-out style? is there any special consideration?

**Comment by longxueyuu** [comment]
> Stacks are almost universally implemented in that fashion:

the link you provided says: stack is LIFO, but it is implemented as FIFO in go.vm

**Comment by skx** [comment]
Sorry, you're absolutely right.  That is broken.

I guess it would become an issue if there were nested `call` operations going on.  Will fix ASAP.
